### ISSUE TITLE
`ckan help` is nearly useless

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-cmdline#2]
_From @ToxicFrog on November 23, 2014 13:50_

The offline documentation is extremely sparse, but that's ok, because ckan has a built in help command, right?

Well, not so much:
- `ckan help` doesn't list common options like --debug
- `ckan help <command>` produces the same output as `ckan help`
- Running a command without arguments produces help, but...
  - If it's a command that doesn't *take* arguments, like `update`, it just runs the command
  - Even if it's a command that does, like `install`, it only lists some of the flags, not all of them

The upshot of this is that extremely useful options like `update --repo` or `install --ckanfile` can only be discovered by reading the source.

_Copied from original issue: KSP-CKAN/CKAN#445_

**Comment by pjf** [comment]
Moving back to original issue.
