### ISSUE TITLE
"ckan --verbose" should start the GUI with verbose debugging

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-cmdline#3]
_From @AlexanderDzhoganov on November 21, 2014 17:6_

`ckan` without arguments starts the GUI, one would expect that `ckan --verbose` will start the GUI with verbose logging, instead we get the default help message. I expect this is also true for `--debug` and other such arguments.

_Copied from original issue: KSP-CKAN/CKAN#437_

**Comment by pjf** [comment]
Moving back to original issue. :)
