### ISSUE TITLE
Command-line fails to start GUI when no default instance is selected

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-cmdline#4]
_From @AlexanderDzhoganov on November 21, 2014 17:4_

`ckan gui` fails to start when no default ckan instance is selected with the following error:
`I don't know where KSP is installed.
Use 'ckan ksp help' for assistance on setting this.`

on the other hand running just `ckan` with no arguments work fine. 
This problem does not occur when a default KSP instance has been selected already.

_Copied from original issue: KSP-CKAN/CKAN#436_

**Comment by Dazpoet** [comment]
Is this fixed by https://github.com/KSP-CKAN/CKAN-core/pull/122 ?

**Comment by pjf** [comment]
@Dazpoet : Let's say yes. If it's not, I'm sure one of our many users will tell us. :D
