### ISSUE TITLE
'ckan show' stopped listing files in a package

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN-cmdline#50]
It used to be that a 'ckan show <id>' would show details about a mod, and a list of the included files too. This was particularly useful when running ckan in the pull request jobs on jenkins.

Would be nice if this could be reintroduced :smiling_imp:

**Comment by mgsdk** [comment]
Probably an error that snug in during https://github.com/KSP-CKAN/CKAN-cmdline/pull/45, I'll see if I can figure out a way to fix this.

**Comment by mgsdk** [comment]
Seems #45 was not to blame, but I need to better commentate my changes lest people optimize necessary code away.

On a side note, would love some input on #44. One can really feel the parsing time of the module list when testing for this issue.

**Comment by Ippo343** [comment]
That's most likely my fault, since I just touched the cmdline code in KSP-CKAN/CKAN-cmdline#49

**Comment by hakan42** [comment]
#51 fixed that issue, Jenkins shows the contents of the ckans again. Thanks, @mgsdk

**Comment by mgsdk** [comment]
@Ippo343 My code could probably have been a bit cleaner to begin with, it is a convoluted way to show the information. And it is always appreciated when someone can transform my convoluted if-else constructions into short LINQ statements :)
