### ISSUE TITLE
Support wildcards in remove command

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-cmdline#6]
_From @Ippo343 on November 14, 2014 16:43_

The client should support wildcards, at least in the remove command.

Right now, trying to do `ckan remove *` just returns an error message saying that

    I can't do that, * isn't installed

_Copied from original issue: KSP-CKAN/CKAN#366_

**Comment by Dazpoet** [comment]
This was fixed a while ago through the addition of `--re` to the remove command which supports regexp.

The way of removing every mod is now `ckan remove --re .`
