### ISSUE TITLE
Incorrect client version reported in CLI

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-cmdline#7]
_From @Ippo343 on November 14, 2014 9:35_

Using Galaxy Rise, `ckan.exe` reports the version as 0.0.0.0:

    CKAN Client 0.0.0.0
    MIT License - CKAN Team

_Copied from original issue: KSP-CKAN/CKAN#362_

**Comment by hakan42** [comment]
This is especially complicated now that we have multiple repositories...

Maybe something based on Jenkins build number of the "CKAN" build job ( http://ci.ksp-ckan.org:8080/job/CKAN/ )?

**Comment by AlexanderDzhoganov** [comment]
We should not bump up the DLL version. I repeat **we should not bump up the DLL version**, this will make all plugins and everything that depends on CKAN break, this is because assembly references are resolved by exact version (stupid, stupid). This problem should be solved in another way.

**Comment by pjf** [comment]
Moving back to original issue. :)
